<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_product = $block->getProduct();
?>

<?php if ($_additional = $block->getAdditionalData()): ?>
    <div class="additional-attributes-wrapper table-wrapper">
        <table class="data table additional-attributes" id="product-attribute-specs-table">
            <caption class="table-caption"><?= /* @escapeNotVerified */ __('More Information') ?></caption>
            <tbody>
            <?php foreach ($_additional as $_data): ?>
                <tr>
                    <th class="col label" scope="row">
                        <?= $block->escapeHtml(__($_data['label'])) ?>
                        <span class="tooltip" data-tooltip-content="#tooltip-content-<?= $_data['code'] ?>">?</span>
                        <div class="tooltip-content-wrapper">
                            <div id="tooltip-content-<?= $_data['code'] ?>" class="tooltip-content">
                                <?= $_data['tooltip'] ?>
                            </div>
                        </div>
                    </th>
                    <td class="col data" data-th="<?= $block->escapeHtml(__($_data['label'])) ?>">
                        <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php endif;?>

<script type="text/x-magento-init">
    {
         ".tooltip": {
             "Tooltipster": {
                 "contentCloning": true,
                 "theme": "tooltipster-custom"
             }
         }
    }
</script>