<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper(Magento\Catalog\Helper\Output::class);
    $_product = $block->getProduct();
?>
<?php if ($_additional = $block->getAdditionalData()) :?>
    <div class="additional-attributes-wrapper table-wrapper">
        <table class="data table additional-attributes" id="product-attribute-specs-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('More Information')) ?></caption>
            <tbody>
            <?php foreach ($_additional as $_data) :?>
                <tr>
                    <th class="col label" scope="row">
                        <?= $block->escapeHtml($_data['label']) ?>
                        <?php if (!empty($_data['tooltip'])): ?>
                        <span class="tooltip" data-tooltip-content="#tooltip-content-<?= $_data['code'] ?>">?</span>
                        <div class="tooltip-content-wrapper">
                            <div id="tooltip-content-<?= $_data['code'] ?>" class="tooltip-content">
                                <?= $_data['tooltip'] ?>
                            </div>
                        </div>
                        <?php endif; ?>
                    </th>
                    <td class="col data" data-th="<?= $block->escapeHtmlAttr($_data['label']) ?>"><?= /* @noEscape */ $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php endif;?>

<script type="text/x-magento-init">
    {
         ".tooltip": {
             "Tooltipster": {
                 "contentCloning": true,
                 "theme": "tooltipster-custom"
             }
         }
    }
</script>